export const categories = ['Девушки', 'Дети', 'Животные', 'Цветочные композиции', 'Семейные сцены', 'Винтажные фигурки', 'Коллекционные композиции'];
// Цены в UAH: пересчёт 14.09.2026 по 0.5285 UAH/RUB, округление до 50 грн.
// Источник: https://www.investing.com/currencies/rub-uah
// Демонстрационный каталог. Перед продажами замените сведения и изображения реальными.
const asset = path => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`;

export const products = [
 {id:'girl-and-fawn',name:'Девушка с оленёнком',category:'Девушки',tags:['Коллекционные композиции'],price:12950,images:[asset('/images/product-1.webp')],additionalImages:[{src:asset('/images/product-1.webp'),label:'Лицо и роспись',position:'50% 20%',zoom:2.5},{src:asset('/images/product-1.webp'),label:'Складки платья',position:'50% 55%',zoom:2},{src:asset('/images/product-1.webp'),label:'Цветы и маленький спутник',position:'55% 85%',zoom:2.5}],material:'Фарфор, ручная роспись',height:24,width:18,condition:'Отличное',year:2025,origin:'Авторская коллекция',available:true,featured:true,unique:true,isNew:true,description:'Тихая встреча на лесной опушке. Девушка склоняется к маленькому оленёнку, и между ними возникает доверие, которому не нужны слова. Приглушённый зелёный, тёплая глазурь и крошечные цветы сохраняют это хрупкое мгновение.'},
 {id:'little-reader',name:'Ещё одна страница',category:'Дети',tags:[],price:6750,material:'Фарфор, подглазурная роспись',height:15,width:12,year:2025,unique:false,featured:true,isNew:true,description:'Книга открыта на самой интересной странице. Неспешная история о детстве, воображении и целых мирах, которые помещаются на ладони.'},
 {id:'rabbits',name:'Лесной шёпот',category:'Животные',tags:[],price:5050,material:'Глазурованный фарфор',height:11,width:16,year:2024,unique:false,featured:true,isNew:false,description:'Два маленьких спутника среди первых весенних цветов. Нежная роспись и мягкие линии напоминают о простых радостях, которые всегда рядом.'},
 {id:'roses',name:'Сад в миниатюре',category:'Цветочные композиции',tags:[],price:9600,material:'Фарфор, лепные цветы',height:14,width:15,year:2025,unique:true,featured:false,isNew:true,description:'Лепесток за лепестком распускается маленький сад. Пыльно-розовые цветы и тонкое плетение корзинки приглашают остановиться и рассмотреть каждую деталь.'},
 {id:'mother-and-child',name:'Самое близкое',category:'Семейные сцены',tags:['Коллекционные композиции'],price:11550,material:'Фарфор, ручная роспись',height:22,width:16,year:2024,unique:true,featured:true,isNew:false,description:'Объятие, в котором помещается целый мир. Спокойная композиция о близости, заботе и памяти о самых дорогих людях.'},
 {id:'ballerina',name:'Перед выходом',category:'Винтажные фигурки',tags:['Девушки'],price:8850,material:'Фарфор, золотистая роспись',height:20,width:14,year:2023,unique:true,featured:false,isNew:false,description:'Секунда тишины перед музыкой. Воздушная юбка, тонкий жест и золотистые акценты превращают движение в маленькое произведение искусства.'}
].map((p,i)=>({images:[asset(`/images/product-${i+1}.webp`)],additionalImages:[{src:asset(`/images/product-${i+1}.webp`),label:'Ручная роспись',position:'50% 30%',zoom:2},{src:asset(`/images/product-${i+1}.webp`),label:'Фактура фарфора',position:'50% 65%',zoom:2.4}],available:true,condition:'Отличное',origin:'Авторская коллекция',...p}));
